- name: Get monit summary for all stats process on VSD
  vsd_monit:
    name: "{{vsd_stats}}"
    state: summary
  register: chk
  remote_user: root

- name: Verify vsd-stats-status program on VSD
  fail: msg="Cannot verify vsd-stats-status. Program not running"
  when: chk['state']['vsd-core-status'] != "status ok"

